export const medicines = [
  ["Paracetamol", "Calpol", "500 mg", "tablet", "tablets", "Analgesic", 500, true],
  ["Amoxicillin", "Moxikind-CV", "500 mg + 125 mg", "tablet", "tablets", "Antibiotic", 240, true],
  ["Amoxicillin", "Moxikind", "250 mg / 5 ml", "suspension", "bottles", "Antibiotic", 120, true],
  ["Ceftriaxone", "Monocef", "1 g", "injection", "vials", "Antibiotic", 120, true],
  ["Azithromycin", "Azithral", "500 mg", "tablet", "tablets", "Antibiotic", 120, true],
  ["Metronidazole", "Metrogyl", "500 mg / 100 ml", "infusion", "bags", "Antibiotic", 80, true],
  ["Doxycycline", "Doxy-1", "100 mg", "capsule", "capsules", "Antibiotic", 100, true],
  ["Ciprofloxacin", "Cifran", "500 mg", "tablet", "tablets", "Antibiotic", 100, true],
  ["Insulin glargine", "Lantus", "100 units / ml", "injection", "pens", "Endocrine", 80, true],
  ["Human insulin", "Actrapid", "40 IU / ml", "injection", "vials", "Endocrine", 80, true],
  ["Salbutamol", "Asthalin", "100 mcg", "inhaler", "inhalers", "Respiratory", 60, true],
  ["Budesonide", "Budecort", "0.5 mg / 2 ml", "respules", "respules", "Respiratory", 60, true],
  ["Ipratropium", "Ipravent", "0.5 mg / 2 ml", "respules", "respules", "Respiratory", 60, true],
  ["ORS", "Electral", "WHO formula", "sachet", "sachets", "Rehydration", 400, true],
  ["Ringer's lactate", "RL", "500 ml", "infusion", "bags", "Fluids", 120, true],
  ["Normal saline", "NS", "500 ml", "infusion", "bags", "Fluids", 120, true],
  ["Dextrose", "DNS", "5% / 500 ml", "infusion", "bags", "Fluids", 80, true],
  ["Oxytocin", "Syntocinon", "10 IU / ml", "injection", "ampoules", "Maternal health", 100, true],
  ["Magnesium sulfate", "MgSO4", "50%", "injection", "ampoules", "Maternal health", 80, true],
  ["Misoprostol", "Cytolog", "200 mcg", "tablet", "tablets", "Maternal health", 100, true],
  ["Amlodipine", "Amlong", "5 mg", "tablet", "tablets", "Cardiovascular", 200, true],
  ["Losartan", "Losar", "50 mg", "tablet", "tablets", "Cardiovascular", 160, true],
  ["Atorvastatin", "Atorva", "20 mg", "tablet", "tablets", "Cardiovascular", 160, true],
  ["Aspirin", "Ecosprin", "75 mg", "tablet", "tablets", "Cardiovascular", 200, true],
  ["Furosemide", "Lasix", "40 mg", "tablet", "tablets", "Cardiovascular", 120, true],
  ["Omeprazole", "Omez", "20 mg", "capsule", "capsules", "Gastrointestinal", 180, true],
  ["Ondansetron", "Ondem", "4 mg", "tablet", "tablets", "Gastrointestinal", 100, true],
  ["Pantoprazole", "Pantocid", "40 mg", "injection", "vials", "Gastrointestinal", 100, true],
  ["Diclofenac", "Voveran", "50 mg", "tablet", "tablets", "Analgesic", 120, true],
  ["Ibuprofen", "Brufen", "400 mg", "tablet", "tablets", "Analgesic", 140, true],
  ["Tramadol", "Contramal", "50 mg / ml", "injection", "ampoules", "Analgesic", 60, true],
  ["Heparin", "Heparin", "5,000 IU / ml", "injection", "vials", "Critical care", 50, true],
  ["Enoxaparin", "Clexane", "40 mg", "injection", "syringes", "Critical care", 60, true],
  ["Adrenaline", "Adrenaline", "1 mg / ml", "injection", "ampoules", "Critical care", 60, true],
  ["Dexamethasone", "Dexona", "4 mg / ml", "injection", "ampoules", "Critical care", 60, true],
  ["Povidone iodine", "Betadine", "10%", "solution", "bottles", "Wound care", 80, true],
  ["Chlorhexidine", "Cetrimide", "5%", "solution", "bottles", "Wound care", 60, true],
  ["Metformin", "Glycomet", "500 mg", "tablet", "tablets", "Endocrine", 200, true],
  ["Metformin", "Glycomet", "1000 mg", "tablet", "tablets", "Endocrine", 150, true],
  ["Glimepiride", "Amaryl", "1 mg", "tablet", "tablets", "Endocrine", 150, false],
  ["Glimepiride", "Amaryl", "2 mg", "tablet", "tablets", "Endocrine", 150, true],
  ["Gliclazide", "Diamicron", "80 mg", "tablet", "tablets", "Endocrine", 100, false],
  ["Levothyroxine", "Thyronorm", "50 mcg", "tablet", "tablets", "Endocrine", 120, true],
  ["Levothyroxine", "Thyronorm", "100 mcg", "tablet", "tablets", "Endocrine", 120, true],
  ["Sitagliptin", "Januvia", "50 mg", "tablet", "tablets", "Endocrine", 80, false],
  ["Linagliptin", "Trajenta", "5 mg", "tablet", "tablets", "Endocrine", 80, false],
  ["Dapagliflozin", "Forxiga", "10 mg", "tablet", "tablets", "Endocrine", 90, false],
  ["Empagliflozin", "Jardiance", "10 mg", "tablet", "tablets", "Endocrine", 90, false],
  ["Amlodipine", "Amlong", "10 mg", "tablet", "tablets", "Cardiovascular", 100, true],
  ["Losartan", "Losar", "25 mg", "tablet", "tablets", "Cardiovascular", 100, false],
  ["Telmisartan", "Telma", "40 mg", "tablet", "tablets", "Cardiovascular", 150, true],
  ["Telmisartan", "Telma", "80 mg", "tablet", "tablets", "Cardiovascular", 100, false],
  ["Olmesartan", "Olmec", "20 mg", "tablet", "tablets", "Cardiovascular", 80, false],
  ["Valsartan", "Diovan", "80 mg", "tablet", "tablets", "Cardiovascular", 80, false],
  ["Enalapril", "Envas", "5 mg", "tablet", "tablets", "Cardiovascular", 100, true],
  ["Ramipril", "Cardace", "5 mg", "tablet", "tablets", "Cardiovascular", 120, true],
  ["Metoprolol", "Metolar", "50 mg", "tablet", "tablets", "Cardiovascular", 150, true],
  ["Atenolol", "Tenormin", "50 mg", "tablet", "tablets", "Cardiovascular", 150, true],
  ["Bisoprolol", "Concor", "5 mg", "tablet", "tablets", "Cardiovascular", 100, true],
  ["Carvedilol", "Carloc", "12.5 mg", "tablet", "tablets", "Cardiovascular", 100, true],
  ["Nebivolol", "Nebistar", "5 mg", "tablet", "tablets", "Cardiovascular", 80, false],
  ["Propranolol", "Inderal", "40 mg", "tablet", "tablets", "Cardiovascular", 100, true],
  ["Clonidine", "Catapres", "100 mcg", "tablet", "tablets", "Cardiovascular", 50, false],
  ["Atorvastatin", "Atorva", "40 mg", "tablet", "tablets", "Cardiovascular", 120, true],
  ["Rosuvastatin", "Rozavel", "10 mg", "tablet", "tablets", "Cardiovascular", 150, true],
  ["Rosuvastatin", "Rozavel", "20 mg", "tablet", "tablets", "Cardiovascular", 120, false],
  ["Simvastatin", "Zocor", "20 mg", "tablet", "tablets", "Cardiovascular", 80, true],
  ["Fenofibrate", "Lipicard", "160 mg", "tablet", "tablets", "Cardiovascular", 80, false],
  ["Clopidogrel", "Plavix", "75 mg", "tablet", "tablets", "Cardiovascular", 150, true],
  ["Ticagrelor", "Brilinta", "90 mg", "tablet", "tablets", "Cardiovascular", 100, false],
  ["Prasugrel", "Effient", "10 mg", "tablet", "tablets", "Cardiovascular", 60, false],
  ["Warfarin", "Coumadin", "5 mg", "tablet", "tablets", "Cardiovascular", 80, true],
  ["Acenocoumarol", "Acitrom", "2 mg", "tablet", "tablets", "Cardiovascular", 80, false],
  ["Rivaroxaban", "Xarelto", "15 mg", "tablet", "tablets", "Cardiovascular", 100, false],
  ["Apixaban", "Eliquis", "5 mg", "tablet", "tablets", "Cardiovascular", 100, false],
  ["Dabigatran", "Pradaxa", "110 mg", "capsule", "capsules", "Cardiovascular", 80, false],
  ["Digoxin", "Lanoxin", "0.25 mg", "tablet", "tablets", "Cardiovascular", 60, true],
  ["Amiodarone", "Cordarone", "200 mg", "tablet", "tablets", "Cardiovascular", 60, true],
  ["Diltiazem", "Dilzem", "60 mg", "tablet", "tablets", "Cardiovascular", 80, true],
  ["Verapamil", "Calaptin", "80 mg", "tablet", "tablets", "Cardiovascular", 80, true],
  ["Nitroglycerin", "Nitrostat", "0.5 mg", "tablet", "tablets", "Cardiovascular", 100, true],
  ["Isosorbide dinitrate", "Sorbitrate", "10 mg", "tablet", "tablets", "Cardiovascular", 100, true],
  ["Isosorbide mononitrate", "Monotrate", "20 mg", "tablet", "tablets", "Cardiovascular", 100, false],
  ["Spironolactone", "Aldactone", "25 mg", "tablet", "tablets", "Cardiovascular", 120, true],
  ["Hydrochlorothiazide", "Aquazide", "25 mg", "tablet", "tablets", "Cardiovascular", 100, true],
  ["Chlorthalidone", "CHL", "12.5 mg", "tablet", "tablets", "Cardiovascular", 80, false],
  ["Indapamide", "Natrilix", "1.5 mg", "tablet", "tablets", "Cardiovascular", 80, false],
  ["Amoxicillin", "Moxikind", "500 mg", "capsule", "capsules", "Antibiotic", 200, true],
  ["Amoxicillin + Clavulanic Acid", "Augmentin", "625 mg", "tablet", "tablets", "Antibiotic", 250, true],
  ["Amoxicillin + Clavulanic Acid", "Augmentin", "1.2 g", "injection", "vials", "Antibiotic", 150, true],
  ["Cefixime", "Zifi", "200 mg", "tablet", "tablets", "Antibiotic", 150, true],
  ["Cefpodoxime", "Monocef-O", "200 mg", "tablet", "tablets", "Antibiotic", 120, false],
  ["Cefuroxime", "Ceftum", "500 mg", "tablet", "tablets", "Antibiotic", 120, false],
  ["Cefoperazone + Sulbactam", "Magnex", "1.5 g", "injection", "vials", "Antibiotic", 100, true],
  ["Piperacillin + Tazobactam", "Tazar", "4.5 g", "injection", "vials", "Antibiotic", 100, true],
  ["Meropenem", "Meromac", "1 g", "injection", "vials", "Antibiotic", 100, true],
  ["Imipenem + Cilastatin", "Tienam", "500 mg", "injection", "vials", "Antibiotic", 80, true],
  ["Ertapenem", "Invanz", "1 g", "injection", "vials", "Antibiotic", 60, false],
  ["Levofloxacin", "Loxof", "500 mg", "tablet", "tablets", "Antibiotic", 120, true],
  ["Ofloxacin", "Zenflox", "200 mg", "tablet", "tablets", "Antibiotic", 120, true],
  ["Norfloxacin", "Norflox", "400 mg", "tablet", "tablets", "Antibiotic", 100, false],
  ["Moxifloxacin", "Avelox", "400 mg", "tablet", "tablets", "Antibiotic", 80, false],
  ["Linezolid", "Linid", "600 mg", "tablet", "tablets", "Antibiotic", 80, true],
  ["Vancomycin", "Vancocin", "500 mg", "injection", "vials", "Antibiotic", 80, true],
  ["Teicoplanin", "Targocid", "400 mg", "injection", "vials", "Antibiotic", 60, false],
  ["Clindamycin", "Dalacin C", "300 mg", "capsule", "capsules", "Antibiotic", 100, true],
  ["Nitrofurantoin", "Niftran", "100 mg", "tablet", "tablets", "Antibiotic", 100, true],
  ["Fosfomycin", "Fosirol", "3 g", "sachet", "sachets", "Antibiotic", 60, false],
  ["Cotrimoxazole", "Septran", "800/160 mg", "tablet", "tablets", "Antibiotic", 120, true],
  ["Gentamicin", "Garamycin", "80 mg", "injection", "ampoules", "Antibiotic", 100, true],
  ["Amikacin", "Mikacin", "500 mg", "injection", "vials", "Antibiotic", 100, true],
  ["Tobramycin", "Tobacin", "80 mg", "injection", "vials", "Antibiotic", 60, false],
  ["Azithromycin", "Azithral", "250 mg", "tablet", "tablets", "Antibiotic", 100, true],
  ["Clarithromycin", "Clarigard", "500 mg", "tablet", "tablets", "Antibiotic", 80, true],
  ["Roxithromycin", "Roxid", "150 mg", "tablet", "tablets", "Antibiotic", 80, false],
  ["Fluconazole", "Syscan", "150 mg", "tablet", "tablets", "Antifungal", 120, true],
  ["Itraconazole", "Canditral", "100 mg", "capsule", "capsules", "Antifungal", 100, true],
  ["Voriconazole", "Vfend", "200 mg", "tablet", "tablets", "Antifungal", 60, false],
  ["Posaconazole", "Noxafil", "100 mg", "tablet", "tablets", "Antifungal", 40, false],
  ["Amphotericin B", "Amphotret", "50 mg", "injection", "vials", "Antifungal", 50, true],
  ["Caspofungin", "Cancidas", "50 mg", "injection", "vials", "Antifungal", 40, false],
  ["Micafungin", "Mycamine", "50 mg", "injection", "vials", "Antifungal", 40, false],
  ["Ketoconazole", "Nizral", "200 mg", "tablet", "tablets", "Antifungal", 80, false],
  ["Terbinafine", "Terbinaforce", "250 mg", "tablet", "tablets", "Antifungal", 100, true],
  ["Griseofulvin", "Grisovin", "250 mg", "tablet", "tablets", "Antifungal", 60, false],
  ["Acyclovir", "Zovirax", "400 mg", "tablet", "tablets", "Antiviral", 100, true],
  ["Valacyclovir", "Valcivir", "500 mg", "tablet", "tablets", "Antiviral", 80, false],
  ["Famciclovir", "Famtrex", "250 mg", "tablet", "tablets", "Antiviral", 60, false],
  ["Oseltamivir", "Antiflu", "75 mg", "capsule", "capsules", "Antiviral", 100, true],
  ["Tenofovir", "Tenvir", "300 mg", "tablet", "tablets", "Antiviral", 100, true],
  ["Lamivudine", "Lamivir", "150 mg", "tablet", "tablets", "Antiviral", 100, true],
  ["Efavirenz", "Efcure", "600 mg", "tablet", "tablets", "Antiviral", 80, true],
  ["Lopinavir + Ritonavir", "Lopimune", "200/50 mg", "tablet", "tablets", "Antiviral", 80, true],
  ["Dolutegravir", "Instgra", "50 mg", "tablet", "tablets", "Antiviral", 80, true],
  ["Sofosbuvir", "Hepcinat", "400 mg", "tablet", "tablets", "Antiviral", 60, false],
  ["Velpatasvir", "Velpanat", "100 mg", "tablet", "tablets", "Antiviral", 60, false],
  ["Entecavir", "Entavir", "0.5 mg", "tablet", "tablets", "Antiviral", 60, false],
  ["Albendazole", "Zentel", "400 mg", "tablet", "tablets", "Antihelminthic", 150, true],
  ["Mebendazole", "Mebex", "100 mg", "tablet", "tablets", "Antihelminthic", 100, true],
  ["Ivermectin", "Ivecop", "12 mg", "tablet", "tablets", "Antihelminthic", 120, true],
  ["Diethylcarbamazine", "Banocide", "100 mg", "tablet", "tablets", "Antihelminthic", 100, true],
  ["Artemether + Lumefantrine", "Lumerax", "80/480 mg", "tablet", "tablets", "Anti-malarial", 120, true],
  ["Artesunate", "Faligo", "60 mg", "injection", "vials", "Anti-malarial", 100, true],
  ["Chloroquine", "Lariago", "250 mg", "tablet", "tablets", "Anti-malarial", 100, true],
  ["Primaquine", "Malarid", "15 mg", "tablet", "tablets", "Anti-malarial", 80, true],
  ["Quinine", "Rez-Q", "300 mg", "tablet", "tablets", "Anti-malarial", 60, true],
  ["Mefloquine", "Meflotas", "250 mg", "tablet", "tablets", "Anti-malarial", 60, false],
  ["Isoniazid", "Isonex", "300 mg", "tablet", "tablets", "Anti-tuberculosis", 150, true],
  ["Rifampicin", "R-Cin", "450 mg", "capsule", "capsules", "Anti-tuberculosis", 150, true],
  ["Pyrazinamide", "PZA", "750 mg", "tablet", "tablets", "Anti-tuberculosis", 120, true],
  ["Ethambutol", "Combutol", "800 mg", "tablet", "tablets", "Anti-tuberculosis", 120, true],
  ["Streptomycin", "Ambistryn", "1 g", "injection", "vials", "Anti-tuberculosis", 100, true],
  ["Bedaquiline", "Sirturo", "100 mg", "tablet", "tablets", "Anti-tuberculosis", 40, false],
  ["Delamanid", "Deltyba", "50 mg", "tablet", "tablets", "Anti-tuberculosis", 40, false],
  ["Cycloserine", "Coxerin", "250 mg", "capsule", "capsules", "Anti-tuberculosis", 60, true],
  ["Ethionamide", "Ethide", "250 mg", "tablet", "tablets", "Anti-tuberculosis", 60, true],
  ["PAS", "Paser", "4 g", "sachet", "sachets", "Anti-tuberculosis", 40, true],
  ["Pantoprazole", "Pantocid", "40 mg", "tablet", "tablets", "Gastrointestinal", 200, true],
  ["Rabeprazole", "Rablet", "20 mg", "tablet", "tablets", "Gastrointestinal", 150, false],
  ["Esomeprazole", "Nexpro", "40 mg", "tablet", "tablets", "Gastrointestinal", 150, true],
  ["Ranitidine", "Rantac", "150 mg", "tablet", "tablets", "Gastrointestinal", 200, true],
  ["Famotidine", "Famtac", "40 mg", "tablet", "tablets", "Gastrointestinal", 100, false],
  ["Domperidone", "Domstal", "10 mg", "tablet", "tablets", "Gastrointestinal", 150, true],
  ["Metoclopramide", "Perinorm", "10 mg", "tablet", "tablets", "Gastrointestinal", 120, true],
  ["Levosulpiride", "Lesuride", "25 mg", "tablet", "tablets", "Gastrointestinal", 100, false],
  ["Itopride", "Ganaton", "50 mg", "tablet", "tablets", "Gastrointestinal", 80, false],
  ["Mebeverine", "Colospa", "135 mg", "tablet", "tablets", "Gastrointestinal", 100, false],
  ["Drotaverine", "Drotin", "80 mg", "tablet", "tablets", "Gastrointestinal", 120, true],
  ["Hyoscine butylbromide", "Buscopan", "10 mg", "tablet", "tablets", "Gastrointestinal", 100, true],
  ["Dicyclomine", "Cyclopam", "20 mg", "tablet", "tablets", "Gastrointestinal", 100, true],
  ["Loperamide", "Eldoper", "2 mg", "capsule", "capsules", "Gastrointestinal", 150, true],
  ["Racecadotril", "Redotil", "100 mg", "capsule", "capsules", "Gastrointestinal", 100, false],
  ["Bisacodyl", "Dulcolax", "5 mg", "tablet", "tablets", "Gastrointestinal", 120, true],
  ["Lactulose", "Duphalac", "10 g / 15 ml", "syrup", "bottles", "Gastrointestinal", 150, true],
  ["PEG 3350", "Pegclear", "17 g", "sachet", "sachets", "Gastrointestinal", 100, false],
  ["Sodium picosulfate", "Cremalax", "5 mg / 5 ml", "syrup", "bottles", "Gastrointestinal", 80, false],
  ["Ursodeoxycholic acid", "Udiliv", "300 mg", "tablet", "tablets", "Gastrointestinal", 100, true],
  ["Pancreatin", "Creon", "10000 U", "capsule", "capsules", "Gastrointestinal", 80, true],
  ["Silymarin", "Silybon", "140 mg", "tablet", "tablets", "Gastrointestinal", 60, false],
  ["L-ornithine L-aspartate", "HepaMerz", "5 g", "sachet", "sachets", "Gastrointestinal", 60, false],
  ["Mesalazine", "Mesacol", "400 mg", "tablet", "tablets", "Gastrointestinal", 100, true],
  ["Sulfasalazine", "Saaz", "500 mg", "tablet", "tablets", "Gastrointestinal", 80, true],
  ["Budesonide (GI)", "Budenofalk", "3 mg", "capsule", "capsules", "Gastrointestinal", 60, false],
  ["Saccharomyces boulardii", "Econorm", "250 mg", "sachet", "sachets", "Gastrointestinal", 120, false],
  ["Bacillus clausii", "Enterogermina", "2 billion spores", "suspension", "bottles", "Gastrointestinal", 150, false],
  ["Pre/Probiotics", "Vizylac", "Blend", "capsule", "capsules", "Gastrointestinal", 150, true],
  ["Paracetamol", "Calpol", "650 mg", "tablet", "tablets", "Analgesic", 400, true],
  ["Paracetamol", "Crocin", "125 mg / 5 ml", "syrup", "bottles", "Analgesic", 200, true],
  ["Paracetamol", "Neomol", "10 mg / ml", "infusion", "bags", "Analgesic", 150, true],
  ["Ibuprofen", "Brufen", "200 mg", "tablet", "tablets", "Analgesic", 150, true],
  ["Ibuprofen", "Ibugesic", "100 mg / 5 ml", "syrup", "bottles", "Analgesic", 120, true],
  ["Diclofenac", "Voveran", "75 mg", "injection", "ampoules", "Analgesic", 150, true],
  ["Diclofenac", "Volini", "1%", "gel", "tubes", "Analgesic", 200, true],
  ["Aceclofenac", "Zerodol", "100 mg", "tablet", "tablets", "Analgesic", 200, true],
  ["Ketorolac", "Ketorol", "10 mg", "tablet", "tablets", "Analgesic", 100, false],
  ["Ketorolac", "Ketorol", "30 mg", "injection", "ampoules", "Analgesic", 100, true],
  ["Piroxicam", "Dolonex", "20 mg", "tablet", "tablets", "Analgesic", 100, false],
  ["Meloxicam", "Muvera", "7.5 mg", "tablet", "tablets", "Analgesic", 80, false],
  ["Naproxen", "Naprosyn", "250 mg", "tablet", "tablets", "Analgesic", 100, true],
  ["Etoricoxib", "Nucoxia", "90 mg", "tablet", "tablets", "Analgesic", 150, false],
  ["Celecoxib", "Celact", "200 mg", "capsule", "capsules", "Analgesic", 100, false],
  ["Tramadol", "Contramal", "50 mg", "tablet", "tablets", "Analgesic", 120, true],
  ["Tapentadol", "Tydol", "50 mg", "tablet", "tablets", "Analgesic", 80, false],
  ["Buprenorphine", "Buprigesic", "0.3 mg", "injection", "ampoules", "Analgesic", 60, true],
  ["Fentanyl", "Durogesic", "25 mcg / hr", "patch", "patches", "Analgesic", 40, true],
  ["Morphine", "Morphine", "10 mg", "tablet", "tablets", "Analgesic", 100, true],
  ["Morphine", "Morphine", "15 mg", "injection", "ampoules", "Analgesic", 100, true],
  ["Pregabalin", "Lyrica", "75 mg", "capsule", "capsules", "Neurology", 150, true],
  ["Gabapentin", "Gabapin", "300 mg", "capsule", "capsules", "Neurology", 120, true],
  ["Amitriptyline", "Tryptomer", "10 mg", "tablet", "tablets", "Psychiatry", 150, true],
  ["Amitriptyline", "Tryptomer", "25 mg", "tablet", "tablets", "Psychiatry", 120, true],
  ["Nortriptyline", "Sensival", "25 mg", "tablet", "tablets", "Psychiatry", 100, false],
  ["Duloxetine", "Symbal", "20 mg", "capsule", "capsules", "Psychiatry", 100, false],
  ["Escitalopram", "Nexito", "10 mg", "tablet", "tablets", "Psychiatry", 150, true],
  ["Sertraline", "Daxid", "50 mg", "tablet", "tablets", "Psychiatry", 120, true],
  ["Fluoxetine", "Fludac", "20 mg", "capsule", "capsules", "Psychiatry", 120, true],
  ["Paroxetine", "Pari", "20 mg", "tablet", "tablets", "Psychiatry", 100, false],
  ["Fluvoxamine", "Fluvoxin", "50 mg", "tablet", "tablets", "Psychiatry", 80, false],
  ["Venlafaxine", "Venlor", "75 mg", "capsule", "capsules", "Psychiatry", 100, true],
  ["Desvenlafaxine", "Dveniz", "50 mg", "tablet", "tablets", "Psychiatry", 80, false],
  ["Mirtazapine", "Mirazep", "15 mg", "tablet", "tablets", "Psychiatry", 80, false],
  ["Bupropion", "Wellbutrin", "150 mg", "tablet", "tablets", "Psychiatry", 60, false],
  ["Alprazolam", "Alprax", "0.25 mg", "tablet", "tablets", "Psychiatry", 150, true],
  ["Alprazolam", "Alprax", "0.5 mg", "tablet", "tablets", "Psychiatry", 120, true],
  ["Clonazepam", "Zapiz", "0.5 mg", "tablet", "tablets", "Psychiatry", 150, true],
  ["Lorazepam", "Ativan", "1 mg", "tablet", "tablets", "Psychiatry", 120, true],
  ["Diazepam", "Valium", "5 mg", "tablet", "tablets", "Psychiatry", 100, true],
  ["Zolpidem", "Zolfresh", "10 mg", "tablet", "tablets", "Psychiatry", 100, false],
  ["Zopiclone", "Zopicon", "7.5 mg", "tablet", "tablets", "Psychiatry", 80, false],
  ["Haloperidol", "Serenace", "5 mg", "tablet", "tablets", "Psychiatry", 100, true],
  ["Haloperidol", "Serenace", "5 mg / ml", "injection", "ampoules", "Psychiatry", 100, true],
  ["Risperidone", "Sizodon", "2 mg", "tablet", "tablets", "Psychiatry", 120, true],
  ["Olanzapine", "Oleanz", "5 mg", "tablet", "tablets", "Psychiatry", 120, true],
  ["Quetiapine", "Qutan", "50 mg", "tablet", "tablets", "Psychiatry", 100, true],
  ["Clozapine", "Lozapin", "25 mg", "tablet", "tablets", "Psychiatry", 80, true],
  ["Aripiprazole", "Arip MT", "10 mg", "tablet", "tablets", "Psychiatry", 80, false],
  ["Lithium", "Lithosun", "300 mg", "tablet", "tablets", "Psychiatry", 100, true],
  ["Sodium Valproate", "Valparin", "200 mg", "tablet", "tablets", "Neurology", 150, true],
  ["Divalproex", "Divalpro", "250 mg", "tablet", "tablets", "Neurology", 120, true],
  ["Levetiracetam", "Keppra", "500 mg", "tablet", "tablets", "Neurology", 150, true],
  ["Levetiracetam", "Keppra", "100 mg / ml", "injection", "vials", "Neurology", 100, true],
  ["Phenytoin", "Eptoin", "100 mg", "tablet", "tablets", "Neurology", 150, true],
  ["Phenytoin", "Eptoin", "50 mg / ml", "injection", "ampoules", "Neurology", 100, true],
  ["Carbamazepine", "Tegrital", "200 mg", "tablet", "tablets", "Neurology", 150, true],
  ["Oxcarbazepine", "Oxetal", "300 mg", "tablet", "tablets", "Neurology", 100, false],
  ["Lacosamide", "Lacosam", "50 mg", "tablet", "tablets", "Neurology", 80, false],
  ["Topiramate", "Topamac", "25 mg", "tablet", "tablets", "Neurology", 80, false],
  ["Zonisamide", "Zonisep", "50 mg", "capsule", "capsules", "Neurology", 60, false],
  ["Donepezil", "Donep", "5 mg", "tablet", "tablets", "Neurology", 100, false],
  ["Memantine", "Admenta", "5 mg", "tablet", "tablets", "Neurology", 80, false],
  ["Rivastigmine", "Exelon", "1.5 mg", "capsule", "capsules", "Neurology", 60, false],
  ["Levodopa + Carbidopa", "Syndopa", "250/25 mg", "tablet", "tablets", "Neurology", 120, true],
  ["Pramipexole", "Pramipex", "0.25 mg", "tablet", "tablets", "Neurology", 100, false],
  ["Ropinirole", "Ropar", "1 mg", "tablet", "tablets", "Neurology", 80, false],
  ["Trihexyphenidyl", "Pacitane", "2 mg", "tablet", "tablets", "Neurology", 100, true],
  ["Amantadine", "Amantrel", "100 mg", "capsule", "capsules", "Neurology", 60, false],
  ["Cetirizine", "Cetzine", "10 mg", "tablet", "tablets", "Antihistamine", 250, true],
  ["Levocetirizine", "1-AL", "5 mg", "tablet", "tablets", "Antihistamine", 250, true],
  ["Loratadine", "Lorfast", "10 mg", "tablet", "tablets", "Antihistamine", 150, true],
  ["Desloratadine", "Dazit", "5 mg", "tablet", "tablets", "Antihistamine", 100, false],
  ["Fexofenadine", "Allegra", "120 mg", "tablet", "tablets", "Antihistamine", 150, true],
  ["Fexofenadine", "Allegra", "180 mg", "tablet", "tablets", "Antihistamine", 120, false],
  ["Chlorpheniramine", "Avil", "25 mg", "tablet", "tablets", "Antihistamine", 200, true],
  ["Chlorpheniramine", "Avil", "22.75 mg / ml", "injection", "ampoules", "Antihistamine", 150, true],
  ["Promethazine", "Phenergan", "25 mg", "tablet", "tablets", "Antihistamine", 100, true],
  ["Promethazine", "Phenergan", "25 mg / ml", "injection", "ampoules", "Antihistamine", 100, true],
  ["Cyproheptadine", "Practin", "4 mg", "tablet", "tablets", "Antihistamine", 100, false],
  ["Hydroxyzine", "Atarax", "25 mg", "tablet", "tablets", "Antihistamine", 120, true],
  ["Montelukast", "Montair", "10 mg", "tablet", "tablets", "Respiratory", 200, true],
  ["Levocetirizine + Montelukast", "Montair LC", "5/10 mg", "tablet", "tablets", "Respiratory", 250, true],
  ["Theophylline", "Deriphyllin", "300 mg", "tablet", "tablets", "Respiratory", 100, true],
  ["Doxofylline", "Doxovent", "400 mg", "tablet", "tablets", "Respiratory", 100, false],
  ["Formoterol + Budesonide", "Foracort", "6/200 mcg", "inhaler", "inhalers", "Respiratory", 150, true],
  ["Formoterol + Budesonide", "Foracort", "6/400 mcg", "inhaler", "inhalers", "Respiratory", 120, true],
  ["Salmeterol + Fluticasone", "Seroflo", "25/250 mcg", "inhaler", "inhalers", "Respiratory", 120, true],
  ["Tiotropium", "Tiova", "9 mcg", "inhaler", "inhalers", "Respiratory", 100, true],
  ["Levosalbutamol", "Levolin", "50 mcg", "inhaler", "inhalers", "Respiratory", 120, true],
  ["Levosalbutamol", "Levolin", "1.25 mg / 2.5 ml", "respules", "respules", "Respiratory", 120, true],
  ["Ambroxol", "Ambril", "30 mg / 5 ml", "syrup", "bottles", "Respiratory", 150, true],
  ["Bromhexine", "Bromhexine", "8 mg / 5 ml", "syrup", "bottles", "Respiratory", 100, false],
  ["Dextromethorphan", "Alex", "10 mg / 5 ml", "syrup", "bottles", "Respiratory", 150, true],
  ["Guaifenesin", "Glycodin", "100 mg / 5 ml", "syrup", "bottles", "Respiratory", 120, true],
  ["Fluticasone", "Furamist", "50 mcg", "spray", "bottles", "Respiratory", 100, true],
  ["Mometasone", "Metaspray", "50 mcg", "spray", "bottles", "Respiratory", 100, false],
  ["Ciclesonide", "Zetonna", "80 mcg", "spray", "bottles", "Respiratory", 60, false],
  ["Methylprednisolone", "Medrol", "4 mg", "tablet", "tablets", "Endocrine", 150, true],
  ["Methylprednisolone", "Medrol", "16 mg", "tablet", "tablets", "Endocrine", 120, true],
  ["Methylprednisolone", "Solu-Medrol", "1 g", "injection", "vials", "Endocrine", 80, true],
  ["Prednisolone", "Wysolone", "5 mg", "tablet", "tablets", "Endocrine", 200, true],
  ["Prednisolone", "Wysolone", "10 mg", "tablet", "tablets", "Endocrine", 150, true],
  ["Prednisolone", "Wysolone", "20 mg", "tablet", "tablets", "Endocrine", 150, true],
  ["Hydrocortisone", "Primacort", "100 mg", "injection", "vials", "Endocrine", 120, true],
  ["Deflazacort", "Defza", "6 mg", "tablet", "tablets", "Endocrine", 100, false],
  ["Deflazacort", "Defza", "30 mg", "tablet", "tablets", "Endocrine", 80, false],
  ["Triamcinolone", "Kenacort", "40 mg / ml", "injection", "vials", "Endocrine", 100, true],
  ["Triamcinolone", "Kenacort", "0.1%", "paste", "tubes", "Dermatology", 80, true],
  ["Betamethasone", "Betnovate", "0.1%", "cream", "tubes", "Dermatology", 150, true],
  ["Clobetasol", "Tenovate", "0.05%", "cream", "tubes", "Dermatology", 150, true],
  ["Halobetasol", "Halox", "0.05%", "cream", "tubes", "Dermatology", 100, false],
  ["Mometasone (Topical)", "Momate", "0.1%", "cream", "tubes", "Dermatology", 120, false],
  ["Tacrolimus (Topical)", "Takfa", "0.1%", "ointment", "tubes", "Dermatology", 100, false],
  ["Pimecrolimus", "Elidel", "1%", "cream", "tubes", "Dermatology", 60, false],
  ["Fusidic acid", "Fucidin", "2%", "cream", "tubes", "Dermatology", 120, true],
  ["Mupirocin", "T-Bact", "2%", "ointment", "tubes", "Dermatology", 120, true],
  ["Silver sulfadiazine", "Silverex", "1%", "cream", "tubes", "Wound care", 150, true],
  ["Clotrimazole", "Candid", "1%", "cream", "tubes", "Dermatology", 200, true],
  ["Clotrimazole", "Candid", "1%", "powder", "bottles", "Dermatology", 150, true],
  ["Miconazole", "Zole", "2%", "cream", "tubes", "Dermatology", 120, true],
  ["Ketoconazole", "Nizral", "2%", "cream", "tubes", "Dermatology", 150, true],
  ["Ketoconazole", "Nizral", "2%", "shampoo", "bottles", "Dermatology", 100, false],
  ["Luliconazole", "Lulifin", "1%", "cream", "tubes", "Dermatology", 100, false],
  ["Amorolfine", "Loceryl", "5%", "lacquer", "bottles", "Dermatology", 60, false],
  ["Permethrin", "Perlice", "5%", "cream", "tubes", "Dermatology", 120, true],
  ["Permethrin", "Perlice", "1%", "lotion", "bottles", "Dermatology", 100, true],
  ["Gamma benzene hexachloride", "Scaboma", "1%", "lotion", "bottles", "Dermatology", 100, true],
  ["Benzyl benzoate", "Ascabiol", "25%", "lotion", "bottles", "Dermatology", 80, true],
  ["Calamine", "Caladryl", "8%", "lotion", "bottles", "Dermatology", 150, true],
  ["Minoxidil", "Mintop", "5%", "solution", "bottles", "Dermatology", 80, false],
  ["Finasteride", "Finpecia", "1 mg", "tablet", "tablets", "Dermatology", 80, false],
  ["Isotretinoin", "Sotret", "20 mg", "capsule", "capsules", "Dermatology", 100, false],
  ["Adapalene", "Adaferin", "0.1%", "gel", "tubes", "Dermatology", 100, false],
  ["Benzoyl peroxide", "Brevoxyl", "2.5%", "gel", "tubes", "Dermatology", 120, true],
  ["Clindamycin (Topical)", "Clindac A", "1%", "gel", "tubes", "Dermatology", 150, true],
  ["Salicylic acid", "Salicylix", "6%", "ointment", "tubes", "Dermatology", 100, true],
  ["Coal tar", "Ionax T", "4.25%", "shampoo", "bottles", "Dermatology", 80, false],
  ["Lidocaine", "Xylocaine", "2%", "jelly", "tubes", "Anesthesia", 150, true],
  ["Lidocaine", "Xylocaine", "2%", "injection", "vials", "Anesthesia", 150, true],
  ["Lidocaine + Adrenaline", "Xylocaine Adrenaline", "2% + 1:200k", "injection", "vials", "Anesthesia", 120, true],
  ["Bupivacaine", "Sensorcaine", "0.5%", "injection", "vials", "Anesthesia", 120, true],
  ["Bupivacaine", "Sensorcaine Heavy", "0.5%", "injection", "ampoules", "Anesthesia", 100, true],
  ["Ropivacaine", "Ropin", "0.2%", "injection", "vials", "Anesthesia", 80, false],
  ["Propofol", "Profol", "1%", "injection", "vials", "Anesthesia", 100, true],
  ["Ketamine", "Aneket", "50 mg / ml", "injection", "vials", "Anesthesia", 100, true],
  ["Midazolam", "Mezolam", "1 mg / ml", "injection", "vials", "Anesthesia", 120, true],
  ["Thiopental", "Pentothal", "500 mg", "injection", "vials", "Anesthesia", 80, true],
  ["Succinylcholine", "Scoline", "50 mg / ml", "injection", "vials", "Anesthesia", 80, true],
  ["Atracurium", "Tracrium", "10 mg / ml", "injection", "ampoules", "Anesthesia", 100, true],
  ["Vecuronium", "Norcuron", "4 mg", "injection", "vials", "Anesthesia", 100, true],
  ["Rocuronium", "Esmeron", "10 mg / ml", "injection", "vials", "Anesthesia", 80, true],
  ["Neostigmine", "Myostigmin", "0.5 mg / ml", "injection", "ampoules", "Anesthesia", 80, true],
  ["Glycopyrrolate", "Pyrolate", "0.2 mg / ml", "injection", "ampoules", "Anesthesia", 80, true],
  ["Atropine", "Tropine", "0.6 mg / ml", "injection", "ampoules", "Anesthesia", 120, true],
  ["Ephedrine", "Efcorlin", "30 mg / ml", "injection", "ampoules", "Critical care", 100, true],
  ["Noradrenaline", "Adrenor", "2 mg / ml", "injection", "ampoules", "Critical care", 120, true],
  ["Dopamine", "Domin", "40 mg / ml", "injection", "ampoules", "Critical care", 100, true],
  ["Dobutamine", "Dotamin", "50 mg / ml", "injection", "ampoules", "Critical care", 100, true],
  ["Vasopressin", "Pressin", "20 IU / ml", "injection", "ampoules", "Critical care", 80, true],
  ["Amiodarone (IV)", "Cordarone IV", "150 mg / 3 ml", "injection", "ampoules", "Critical care", 80, true],
  ["Adenosine", "Adenocor", "3 mg / ml", "injection", "ampoules", "Critical care", 60, true],
  ["Labetalol", "Lobet", "5 mg / ml", "injection", "ampoules", "Critical care", 100, true],
  ["Sodium Nitroprusside", "Pruside", "50 mg", "injection", "vials", "Critical care", 60, true],
  ["Nitroglycerin (IV)", "NTG", "5 mg / ml", "injection", "ampoules", "Critical care", 100, true],
  ["Calcium Gluconate", "Calcium Gluconate", "10%", "injection", "ampoules", "Critical care", 120, true],
  ["Potassium Chloride", "KCL", "150 mg / ml", "injection", "ampoules", "Critical care", 150, true],
  ["Sodium Bicarbonate", "Soda Bicarb", "7.5%", "injection", "ampoules", "Critical care", 150, true],
  ["Magnesium Sulfate", "MagSulph", "25%", "injection", "ampoules", "Critical care", 100, true],
  ["Dextrose 25%", "D25", "25%", "infusion", "ampoules", "Critical care", 120, true],
  ["Dextrose 50%", "D50", "50%", "infusion", "ampoules", "Critical care", 100, true],
  ["Mannitol", "Mannitol", "20%", "infusion", "bags", "Critical care", 120, true],
  ["Hydroxyethyl Starch", "Voluven", "6%", "infusion", "bags", "Fluids", 80, false],
  ["Gelatin", "Haemaccel", "3.5%", "infusion", "bags", "Fluids", 80, false],
  ["Albumin", "Albumin", "20%", "infusion", "vials", "Fluids", 60, true],
  ["Water for Injection", "WFI", "10 ml", "injection", "ampoules", "Fluids", 300, true],
  ["Mifepristone", "MTP", "200 mg", "tablet", "tablets", "Maternal health", 80, true],
  ["Ethamsylate", "Sylate", "500 mg", "tablet", "tablets", "Maternal health", 100, true],
  ["Tranexamic acid", "Pause", "500 mg", "tablet", "tablets", "Maternal health", 120, true],
  ["Tranexamic acid", "Pause", "500 mg / 5 ml", "injection", "ampoules", "Maternal health", 100, true],
  ["Dinoprostone", "Cerviprime", "0.5 mg", "gel", "tubes", "Maternal health", 60, true],
  ["Carboprost", "Prostodin", "250 mcg", "injection", "ampoules", "Maternal health", 60, true],
  ["Methylergometrine", "Methergin", "0.2 mg", "injection", "ampoules", "Maternal health", 100, true],
  ["Labetalol (Oral)", "Lobet", "100 mg", "tablet", "tablets", "Maternal health", 100, true],
  ["Methyldopa", "Alphadopa", "250 mg", "tablet", "tablets", "Maternal health", 100, true],
  ["Nifedipine", "Nicardia", "10 mg", "tablet", "tablets", "Maternal health", 150, true],
  ["Isoxsuprine", "Duvadilan", "10 mg", "tablet", "tablets", "Maternal health", 80, false],
  ["Progesterone", "Susten", "200 mg", "capsule", "capsules", "Maternal health", 120, true],
  ["Dydrogesterone", "Duphaston", "10 mg", "tablet", "tablets", "Maternal health", 100, false],
  ["Norethisterone", "Regestrone", "5 mg", "tablet", "tablets", "Maternal health", 150, true],
  ["Levonorgestrel", "i-pill", "1.5 mg", "tablet", "tablets", "Maternal health", 200, true],
  ["Ethinyl Estradiol + Levonorgestrel", "Mala-D", "0.03/0.15 mg", "tablet", "tablets", "Maternal health", 200, true],
  ["Letrozole", "Letroz", "2.5 mg", "tablet", "tablets", "Oncology", 100, true],
  ["Anastrozole", "Armotraz", "1 mg", "tablet", "tablets", "Oncology", 80, false],
  ["Tamoxifen", "Cytotam", "20 mg", "tablet", "tablets", "Oncology", 100, true],
  ["Bicalutamide", "Calutide", "50 mg", "tablet", "tablets", "Oncology", 80, false],
  ["Imatinib", "Veenat", "400 mg", "tablet", "tablets", "Oncology", 100, true],
  ["Gefitinib", "Geftinat", "250 mg", "tablet", "tablets", "Oncology", 80, false],
  ["Erlotinib", "Erlocip", "150 mg", "tablet", "tablets", "Oncology", 60, false],
  ["Capecitabine", "Xeloda", "500 mg", "tablet", "tablets", "Oncology", 80, true],
  ["Methotrexate", "Folitrax", "7.5 mg", "tablet", "tablets", "Oncology", 100, true],
  ["Methotrexate", "Folitrax", "50 mg", "injection", "vials", "Oncology", 80, true],
  ["Cyclophosphamide", "Endoxan", "500 mg", "injection", "vials", "Oncology", 80, true],
  ["Fluorouracil", "Fluracil", "500 mg", "injection", "vials", "Oncology", 80, true],
  ["Doxorubicin", "Adriamycin", "50 mg", "injection", "vials", "Oncology", 60, true],
  ["Paclitaxel", "Intaxel", "100 mg", "injection", "vials", "Oncology", 60, true],
  ["Cisplatin", "Cytoplatin", "50 mg", "injection", "vials", "Oncology", 60, true],
  ["Carboplatin", "Kemocarb", "450 mg", "injection", "vials", "Oncology", 60, true],
  ["Rituximab", "Ristova", "500 mg", "injection", "vials", "Oncology", 40, true],
  ["Trastuzumab", "Herceptin", "440 mg", "injection", "vials", "Oncology", 40, true],
  ["Bevacizumab", "Avastin", "100 mg", "injection", "vials", "Oncology", 40, false],
  ["Filgrastim", "Neukine", "300 mcg", "injection", "vials", "Oncology", 60, true],
  ["Pegfilgrastim", "Peggrafeel", "6 mg", "injection", "vials", "Oncology", 40, false],
  ["Erythropoietin", "Erypro", "4000 IU", "injection", "vials", "Hematology", 80, true],
  ["Iron Sucrose", "Orofer S", "100 mg / 5 ml", "injection", "ampoules", "Hematology", 120, true],
  ["Ferric Carboxymaltose", "Ferinject", "500 mg", "injection", "vials", "Hematology", 60, false],
  ["Ferrous Ascorbate", "Orofer XT", "100 mg", "tablet", "tablets", "Hematology", 250, true],
  ["Ferrous Sulfate", "Fersolate", "200 mg", "tablet", "tablets", "Hematology", 300, true],
  ["Folic Acid", "Folvite", "5 mg", "tablet", "tablets", "Hematology", 300, true],
  ["Vitamin B12", "Neurobion", "1000 mcg", "injection", "ampoules", "Nutritional supplement", 200, true],
  ["Methylcobalamin", "Nurokind", "1500 mcg", "tablet", "tablets", "Nutritional supplement", 250, true],
  ["Vitamin D3", "Calcirol", "60000 IU", "sachet", "sachets", "Nutritional supplement", 300, true],
  ["Vitamin D3", "Arachitol", "600000 IU", "injection", "ampoules", "Nutritional supplement", 100, false],
  ["Calcium Carbonate", "Shelcal", "500 mg", "tablet", "tablets", "Nutritional supplement", 300, true],
  ["Calcium Citrate", "Citracal", "1000 mg", "tablet", "tablets", "Nutritional supplement", 200, false],
  ["Vitamin C", "Limcee", "500 mg", "tablet", "tablets", "Nutritional supplement", 300, true],
  ["Zinc Sulfate", "Zinconia", "50 mg", "tablet", "tablets", "Nutritional supplement", 200, true],
  ["Multivitamin", "Becosules", "Capsule", "capsule", "capsules", "Nutritional supplement", 400, true],
  ["Multivitamin", "Zincovit", "Syrup", "syrup", "bottles", "Nutritional supplement", 300, true],
  ["B-Complex", "Polyzyme", "Syrup", "syrup", "bottles", "Nutritional supplement", 250, true],
  ["Omega-3 Fatty Acids", "Seacod", "300 mg", "capsule", "capsules", "Nutritional supplement", 200, false],
  ["Glucosamine", "Jointace", "500 mg", "tablet", "tablets", "Musculoskeletal", 150, false],
  ["Diacerein", "Dycerin", "50 mg", "capsule", "capsules", "Musculoskeletal", 100, false],
  ["Tamsulosin", "Veltam", "0.4 mg", "capsule", "capsules", "Urology", 150, true],
  ["Silodosin", "Silodal", "8 mg", "capsule", "capsules", "Urology", 100, false],
  ["Alfuzosin", "Alfoo", "10 mg", "tablet", "tablets", "Urology", 100, false],
  ["Finasteride (Urology)", "Finast", "5 mg", "tablet", "tablets", "Urology", 100, true],
  ["Dutasteride", "Dutas", "0.5 mg", "capsule", "capsules", "Urology", 100, false],
  ["Tolterodine", "Roliten", "2 mg", "tablet", "tablets", "Urology", 80, false],
  ["Solifenacin", "Soliten", "5 mg", "tablet", "tablets", "Urology", 80, false],
  ["Mirabegron", "Mirago", "50 mg", "tablet", "tablets", "Urology", 60, false],
  ["Sildenafil", "Viagra", "50 mg", "tablet", "tablets", "Urology", 100, false],
  ["Tadalafil", "Cialis", "10 mg", "tablet", "tablets", "Urology", 100, false],
  ["Flavoxate", "Urispas", "200 mg", "tablet", "tablets", "Urology", 100, false],
  ["Nitrofurantoin", "Martifur", "100 mg", "tablet", "tablets", "Urology", 150, true],
  ["Potassium Citrate", "Potrate", "1080 mg", "tablet", "tablets", "Urology", 100, true],
  ["Allopurinol", "Zyloric", "100 mg", "tablet", "tablets", "Musculoskeletal", 120, true],
  ["Allopurinol", "Zyloric", "300 mg", "tablet", "tablets", "Musculoskeletal", 100, true],
  ["Febuxostat", "Febutaz", "40 mg", "tablet", "tablets", "Musculoskeletal", 100, false],
  ["Colchicine", "Goutnil", "0.5 mg", "tablet", "tablets", "Musculoskeletal", 100, true],
  ["Probenecid", "Probenecid", "500 mg", "tablet", "tablets", "Musculoskeletal", 80, false],
  ["Methocarbamol", "Robinax", "500 mg", "tablet", "tablets", "Musculoskeletal", 100, false],
  ["Thiocolchicoside", "Myoril", "4 mg", "capsule", "capsules", "Musculoskeletal", 120, false],
  ["Tizanidine", "Sirdalud", "2 mg", "tablet", "tablets", "Musculoskeletal", 100, false],
  ["Baclofen", "Lioresal", "10 mg", "tablet", "tablets", "Musculoskeletal", 100, true],
  ["Chlorzoxazone", "Parafon", "250 mg", "tablet", "tablets", "Musculoskeletal", 100, false],
  ["Orphenadrine", "Orphipal", "50 mg", "tablet", "tablets", "Musculoskeletal", 80, false],
  ["Timolol", "Glucomol", "0.5%", "drops", "bottles", "Ophthalmology", 150, true],
  ["Brimonidine", "Alphagan", "0.15%", "drops", "bottles", "Ophthalmology", 100, false],
  ["Dorzolamide", "Dorzox", "2%", "drops", "bottles", "Ophthalmology", 100, false],
  ["Latanoprost", "Xalatan", "0.005%", "drops", "bottles", "Ophthalmology", 120, true],
  ["Bimatoprost", "Lumigan", "0.01%", "drops", "bottles", "Ophthalmology", 100, false],
  ["Travoprost", "Travatan", "0.004%", "drops", "bottles", "Ophthalmology", 100, false],
  ["Cyclopentolate", "Cyclogyl", "1%", "drops", "bottles", "Ophthalmology", 120, true],
  ["Tropicamide", "Tropicacyl", "1%", "drops", "bottles", "Ophthalmology", 150, true],
  ["Atropine (Ophth)", "Atropine", "1%", "drops", "bottles", "Ophthalmology", 120, true],
  ["Homatropine", "Homatropine", "2%", "drops", "bottles", "Ophthalmology", 100, true],
  ["Pilocarpine", "Pilocar", "2%", "drops", "bottles", "Ophthalmology", 100, true],
  ["Nepafenac", "Nevanac", "0.1%", "drops", "bottles", "Ophthalmology", 100, false],
  ["Bromfenac", "Megabrom", "0.09%", "drops", "bottles", "Ophthalmology", 100, false],
  ["Ketorolac (Ophth)", "Acular", "0.5%", "drops", "bottles", "Ophthalmology", 120, true],
  ["Flurbiprofen", "Ocufen", "0.03%", "drops", "bottles", "Ophthalmology", 100, false],
  ["Moxifloxacin (Ophth)", "Vigamox", "0.5%", "drops", "bottles", "Ophthalmology", 150, true],
  ["Gatifloxacin (Ophth)", "Zymar", "0.3%", "drops", "bottles", "Ophthalmology", 120, false],
  ["Ofloxacin (Ophth)", "Ocuflox", "0.3%", "drops", "bottles", "Ophthalmology", 120, true],
  ["Ciprofloxacin (Ophth)", "Ciplox", "0.3%", "drops", "bottles", "Ophthalmology", 150, true],
  ["Tobramycin (Ophth)", "Tobrex", "0.3%", "drops", "bottles", "Ophthalmology", 120, true],
  ["Gentamicin (Ophth)", "Garamycin", "0.3%", "drops", "bottles", "Ophthalmology", 120, true],
  ["Polymyxin B + Bacitracin", "Polysporin", "Ointment", "ointment", "tubes", "Ophthalmology", 100, true],
  ["Chloramphenicol", "Chloromycetin", "1%", "ointment", "tubes", "Ophthalmology", 100, true],
  ["Fluorometholone", "FML", "0.1%", "drops", "bottles", "Ophthalmology", 100, false],
  ["Dexamethasone (Ophth)", "Maxidex", "0.1%", "drops", "bottles", "Ophthalmology", 120, true],
  ["Prednisolone (Ophth)", "Pred Forte", "1%", "drops", "bottles", "Ophthalmology", 120, true],
  ["Loteprednol", "Lotemax", "0.5%", "drops", "bottles", "Ophthalmology", 100, false],
  ["Sodium Hyaluronate", "Hylotears", "0.1%", "drops", "bottles", "Ophthalmology", 150, false],
  ["Carboxymethylcellulose", "Refresh", "0.5%", "drops", "bottles", "Ophthalmology", 200, true],
  ["Hydroxypropyl Methylcellulose", "Tears Naturale", "0.3%", "drops", "bottles", "Ophthalmology", 150, true],
  ["Polyvinyl Alcohol", "Liquifilm", "1.4%", "drops", "bottles", "Ophthalmology", 100, false],
  ["Cyclosporine (Ophth)", "Restasis", "0.05%", "drops", "bottles", "Ophthalmology", 80, false],
  ["Olopatadine", "Patanol", "0.1%", "drops", "bottles", "Ophthalmology", 120, true],
  ["Bepotastine", "Bepreve", "1.5%", "drops", "bottles", "Ophthalmology", 80, false],
  ["Ketotifen", "Zaditor", "0.025%", "drops", "bottles", "Ophthalmology", 100, false],
  ["Azelastine", "Optivar", "0.05%", "drops", "bottles", "Ophthalmology", 80, false],
  ["Naphazoline", "Clearine", "0.1%", "drops", "bottles", "Ophthalmology", 100, false],
  ["Phenylephrine", "Neosynephrine", "5%", "drops", "bottles", "Ophthalmology", 100, true],
  ["Lignocaine (Ophth)", "Paracain", "0.5%", "drops", "bottles", "Ophthalmology", 120, true],
  ["Proparacaine", "Alcaine", "0.5%", "drops", "bottles", "Ophthalmology", 100, true],
  ["Fluorescein", "Fluorescite", "10%", "injection", "ampoules", "Ophthalmology", 60, true],
  ["Trypan Blue", "VisionBlue", "0.06%", "injection", "vials", "Ophthalmology", 60, true],
  ["Hyaluronidase", "Hylase", "1500 IU", "injection", "vials", "Anesthesia", 80, true],
  ["Buprenorphine (Patch)", "BuTrans", "5 mcg / hr", "patch", "patches", "Analgesic", 60, false],
  ["Nicotine", "Nicotex", "2 mg", "gum", "gums", "Psychiatry", 100, false],
  ["Nicotine", "Nicotex", "4 mg", "gum", "gums", "Psychiatry", 100, false],
  ["Varenicline", "Champix", "1 mg", "tablet", "tablets", "Psychiatry", 60, false],
  ["Disulfiram", "Dizone", "250 mg", "tablet", "tablets", "Psychiatry", 80, true],
  ["Acamprosate", "Acamprol", "333 mg", "tablet", "tablets", "Psychiatry", 60, false],
  ["Naltrexone", "Nodict", "50 mg", "tablet", "tablets", "Psychiatry", 80, true],
  ["Flumazenil", "Anexate", "0.5 mg / 5 ml", "injection", "ampoules", "Emergency", 60, true],
  ["Naloxone", "Narcan", "0.4 mg / ml", "injection", "ampoules", "Emergency", 100, true],
  ["Protamine Sulfate", "Protamine", "50 mg", "injection", "vials", "Emergency", 80, true],
  ["Vitamin K1 (Phytomenadione)", "Kenadion", "10 mg / ml", "injection", "ampoules", "Emergency", 120, true],
  ["Tranexamic acid (Emergency)", "Pause", "100 mg / ml", "injection", "ampoules", "Emergency", 150, true],
  ["Anti-Snake Venom", "ASV", "10 ml", "injection", "vials", "Emergency", 100, true],
  ["Anti-Rabies Vaccine", "Rabipur", "1 ml", "injection", "vials", "Emergency", 200, true],
  ["Rabies Immunoglobulin", "Equirab", "300 IU / ml", "injection", "vials", "Emergency", 100, true],
  ["Tetanus Toxoid", "Tetvac", "0.5 ml", "injection", "ampoules", "Emergency", 300, true],
  ["Tetanus Immunoglobulin", "Tetglob", "250 IU", "injection", "vials", "Emergency", 150, true],
  ["Diphtheria Antitoxin", "DAT", "10000 IU", "injection", "vials", "Emergency", 40, true],
  ["Hepatitis B Vaccine", "Engerix-B", "1 ml", "injection", "vials", "Emergency", 200, true],
  ["Hepatitis B Immunoglobulin", "Hepaglob", "200 IU", "injection", "vials", "Emergency", 80, true],
  ["Measles Vaccine", "Measles Vac", "0.5 ml", "injection", "vials", "Emergency", 150, true],
  ["Mumps, Measles, Rubella", "MMR Vac", "0.5 ml", "injection", "vials", "Emergency", 150, true],
  ["Oral Polio Vaccine", "OPV", "2 drops", "suspension", "bottles", "Emergency", 200, true],
  ["BCG Vaccine", "BCG Vac", "0.1 ml", "injection", "vials", "Emergency", 150, true],
  ["Typhoid Vaccine", "Typhbar", "0.5 ml", "injection", "vials", "Emergency", 100, false],
  ["Cholera Vaccine", "Shanchol", "1.5 ml", "suspension", "bottles", "Emergency", 100, false],
  ["Pneumococcal Vaccine", "Prevenar 13", "0.5 ml", "injection", "vials", "Emergency", 100, false],
  ["Influenza Vaccine", "Vaxigrip", "0.5 ml", "injection", "vials", "Emergency", 150, false],
  ["COVID-19 Vaccine", "Covishield", "0.5 ml", "injection", "vials", "Emergency", 300, true],
  ["DPT Vaccine", "Triple Antigen", "0.5 ml", "injection", "vials", "Emergency", 200, true],
  ["Rotavirus Vaccine", "Rotarix", "1.5 ml", "suspension", "bottles", "Emergency", 150, false],
  ["Japanese Encephalitis Vaccine", "Jenvac", "0.5 ml", "injection", "vials", "Emergency", 80, false],
  ["Varicella Vaccine", "Varilrix", "0.5 ml", "injection", "vials", "Emergency", 100, false],
  ["Human Papillomavirus Vaccine", "Gardasil", "0.5 ml", "injection", "vials", "Emergency", 80, false],
  ["Meningococcal Vaccine", "Menactra", "0.5 ml", "injection", "vials", "Emergency", 60, false],
  ["Haemophilus influenzae type B", "HibTITER", "0.5 ml", "injection", "vials", "Emergency", 100, false],
  ["Dengue Vaccine", "Dengvaxia", "0.5 ml", "injection", "vials", "Emergency", 40, false],
  ["Ebola Vaccine", "Ervebo", "1 ml", "injection", "vials", "Emergency", 20, false],
  ["Malaria Vaccine", "Mosquirix", "0.5 ml", "injection", "vials", "Emergency", 20, false],
  ["Anthrax Vaccine", "Biothrax", "0.5 ml", "injection", "vials", "Emergency", 10, false],
  ["Smallpox Vaccine", "ACAM2000", "0.0025 ml", "injection", "vials", "Emergency", 10, false],
  ["Yellow Fever Vaccine", "Stamaril", "0.5 ml", "injection", "vials", "Emergency", 40, false],
  ["Zika Vaccine", "Zikavax", "0.5 ml", "injection", "vials", "Emergency", 10, false],
  ["Typhus Vaccine", "Typhim Vi", "0.5 ml", "injection", "vials", "Emergency", 40, false],
  ["Plague Vaccine", "Plague Vac", "0.5 ml", "injection", "vials", "Emergency", 10, false],
  ["Botulinum Antitoxin", "BAT", "50 ml", "injection", "vials", "Emergency", 10, true],
  ["Diphtheria Antitoxin (Equine)", "DAT Equine", "10000 IU", "injection", "vials", "Emergency", 20, true],
  ["Tetanus Antitoxin (Equine)", "TAT Equine", "1500 IU", "injection", "vials", "Emergency", 40, true],
  ["Gas Gangrene Antitoxin", "GGAT", "10000 IU", "injection", "vials", "Emergency", 20, true],
  ["Black Widow Spider Antivenom", "Antivenin", "2.5 ml", "injection", "vials", "Emergency", 10, true],
  ["Scorpion Antivenom", "Anascorp", "50 ml", "injection", "vials", "Emergency", 20, true],
  ["Stonefish Antivenom", "Stonefish AV", "2000 U", "injection", "vials", "Emergency", 10, true],
  ["Box Jellyfish Antivenom", "Box Jelly AV", "20000 U", "injection", "vials", "Emergency", 10, true],
  ["Tick Antivenom", "Tick AV", "500 U", "injection", "vials", "Emergency", 10, true],
  ["Funnel Web Spider Antivenom", "Funnel Web AV", "100 U", "injection", "vials", "Emergency", 10, true],
  ["Redback Spider Antivenom", "Redback AV", "500 U", "injection", "vials", "Emergency", 10, true],
  ["Brown Snake Antivenom", "Brown Snake AV", "1000 U", "injection", "vials", "Emergency", 10, true],
  ["Tiger Snake Antivenom", "Tiger Snake AV", "3000 U", "injection", "vials", "Emergency", 10, true],
  ["Death Adder Antivenom", "Death Adder AV", "6000 U", "injection", "vials", "Emergency", 10, true],
  ["Taipan Antivenom", "Taipan AV", "12000 U", "injection", "vials", "Emergency", 10, true],
  ["Black Snake Antivenom", "Black Snake AV", "6000 U", "injection", "vials", "Emergency", 10, true],
  ["Sea Snake Antivenom", "Sea Snake AV", "1000 U", "injection", "vials", "Emergency", 10, true],
  ["Polyvalent Snake Antivenom", "Polyvalent AV", "40000 U", "injection", "vials", "Emergency", 20, true],
  ["Paracetamol", "Dolo", "650 mg", "tablet", "tablets", "Analgesic", 400, true],
  ["Amoxicillin", "Novamox", "250 mg", "capsule", "capsules", "Antibiotic", 200, true],
  ["Ceftriaxone", "Oframax", "500 mg", "injection", "vials", "Antibiotic", 150, true],
  ["Azithromycin", "Zithrox", "500 mg", "tablet", "tablets", "Antibiotic", 150, true],
  ["Metronidazole", "Flagyl", "400 mg", "tablet", "tablets", "Antibiotic", 200, true],
  ["Doxycycline", "Tetradox", "100 mg", "capsule", "capsules", "Antibiotic", 150, true],
  ["Ciprofloxacin", "Ciplox", "250 mg", "tablet", "tablets", "Antibiotic", 150, true],
  ["Insulin glargine", "Toujeo", "300 units / ml", "injection", "pens", "Endocrine", 100, true],
  ["Human insulin", "Mixtard", "40 IU / ml", "injection", "vials", "Endocrine", 100, true],
  ["Salbutamol", "Asthalin", "2 mg", "tablet", "tablets", "Respiratory", 100, true],
  ["Budesonide", "Budamet", "100 mcg", "inhaler", "inhalers", "Respiratory", 100, true],
  ["Ipratropium", "Duolin", "500 mcg / 2.5 ml", "respules", "respules", "Respiratory", 100, true],
  ["ORS", "Prolyte", "WHO formula", "sachet", "sachets", "Rehydration", 500, true],
  ["Ringer's lactate", "RL Infusion", "500 ml", "infusion", "bags", "Fluids", 200, true],
  ["Normal saline", "NS Infusion", "100 ml", "infusion", "bags", "Fluids", 200, true],
  ["Dextrose", "D5", "5% / 500 ml", "infusion", "bags", "Fluids", 150, true],
  ["Oxytocin", "Pitocin", "5 IU / ml", "injection", "ampoules", "Maternal health", 120, true],
  ["Magnesium sulfate", "MgSO4", "25%", "injection", "ampoules", "Maternal health", 100, true],
  ["Misoprostol", "Misoprost", "200 mcg", "tablet", "tablets", "Maternal health", 120, true],
  ["Amlodipine", "Amlodep", "2.5 mg", "tablet", "tablets", "Cardiovascular", 150, true],
  ["Losartan", "Repace", "25 mg", "tablet", "tablets", "Cardiovascular", 150, true],
  ["Atorvastatin", "Tonact", "10 mg", "tablet", "tablets", "Cardiovascular", 150, true],
  ["Aspirin", "Disprin", "325 mg", "tablet", "tablets", "Cardiovascular", 200, true],
  ["Furosemide", "Salix", "20 mg", "injection", "ampoules", "Cardiovascular", 150, true],
  ["Omeprazole", "Ocid", "20 mg", "capsule", "capsules", "Gastrointestinal", 200, true],
  ["Ondansetron", "Emeset", "2 mg / ml", "injection", "ampoules", "Gastrointestinal", 150, true],
  ["Pantoprazole", "Pan", "40 mg", "tablet", "tablets", "Gastrointestinal", 250, true],
  ["Diclofenac", "Reactin", "50 mg", "tablet", "tablets", "Analgesic", 150, true],
  ["Ibuprofen", "Combiflam", "400 mg", "tablet", "tablets", "Analgesic", 200, true],
  ["Tramadol", "Supradol", "50 mg / ml", "injection", "ampoules", "Analgesic", 100, true],
  ["Heparin", "Caprin", "5,000 IU / ml", "injection", "vials", "Critical care", 80, true],
  ["Enoxaparin", "Lomux", "60 mg", "injection", "syringes", "Critical care", 80, true],
  ["Adrenaline", "Epinephrine", "1 mg / ml", "injection", "ampoules", "Critical care", 100, true],
  ["Dexamethasone", "Decdan", "4 mg / ml", "injection", "ampoules", "Critical care", 100, true],
  ["Povidone iodine", "Cipladine", "5%", "ointment", "tubes", "Wound care", 150, true],
  ["Chlorhexidine", "Savlon", "1.5%", "solution", "bottles", "Wound care", 120, true],
  ["Cefuroxime", "Zefu", "250 mg", "tablet", "tablets", "Antibiotic", 100, false],
  ["Cefuroxime", "Zefu", "500 mg", "tablet", "tablets", "Antibiotic", 100, false],
  ["Cefaclor", "Keflor", "250 mg", "capsule", "capsules", "Antibiotic", 80, false],
  ["Cefadroxil", "Odoxil", "500 mg", "tablet", "tablets", "Antibiotic", 100, true],
  ["Cephalexin", "Sporidex", "250 mg", "capsule", "capsules", "Antibiotic", 120, true],
  ["Cephalexin", "Sporidex", "500 mg", "capsule", "capsules", "Antibiotic", 150, true],
  ["Cefepime", "Maxipime", "1 g", "injection", "vials", "Antibiotic", 80, true],
  ["Cefotaxime", "Taxim", "1 g", "injection", "vials", "Antibiotic", 120, true],
  ["Cefotaxime", "Taxim", "500 mg", "injection", "vials", "Antibiotic", 100, true],
  ["Aztreonam", "Azenam", "1 g", "injection", "vials", "Antibiotic", 60, false],
  ["Faropenem", "Farobact", "200 mg", "tablet", "tablets", "Antibiotic", 80, false],
  ["Teicoplanin", "Targocid", "200 mg", "injection", "vials", "Antibiotic", 60, false],
  ["Colistin", "Xylistin", "1 MIU", "injection", "vials", "Antibiotic", 60, true],
  ["Polymyxin B", "Poly-B", "500,000 IU", "injection", "vials", "Antibiotic", 60, true],
  ["Daptomycin", "Cubicin", "500 mg", "injection", "vials", "Antibiotic", 40, false],
  ["Tigecycline", "Tygacil", "50 mg", "injection", "vials", "Antibiotic", 40, false],
  ["Minocycline", "Minoz", "100 mg", "tablet", "tablets", "Antibiotic", 80, false],
  ["Erythromycin", "Althrocin", "250 mg", "tablet", "tablets", "Antibiotic", 100, true],
  ["Erythromycin", "Althrocin", "500 mg", "tablet", "tablets", "Antibiotic", 100, true],
  ["Spiramycin", "Rovamycin", "3 MIU", "tablet", "tablets", "Antibiotic", 60, false],
  ["Clindamycin", "Dalacin C", "150 mg", "capsule", "capsules", "Antibiotic", 100, true],
  ["Lincomycin", "Lincocin", "500 mg", "capsule", "capsules", "Antibiotic", 60, false],
  ["Vancomycin", "Vancocin", "1 g", "injection", "vials", "Antibiotic", 80, true],
  ["Fosfomycin", "Monurol", "3 g", "sachet", "sachets", "Antibiotic", 60, false],
  ["Nitrofurantoin", "Niftas", "100 mg", "tablet", "tablets", "Antibiotic", 100, true],
  ["Nalidixic Acid", "Gramoneg", "500 mg", "tablet", "tablets", "Antibiotic", 80, false],
  ["Ofloxacin", "Zenflox", "400 mg", "tablet", "tablets", "Antibiotic", 120, true],
  ["Levofloxacin", "Loxof", "250 mg", "tablet", "tablets", "Antibiotic", 100, true],
  ["Moxifloxacin", "Avelox", "400 mg", "injection", "vials", "Antibiotic", 60, false],
  ["Gemifloxacin", "Factive", "320 mg", "tablet", "tablets", "Antibiotic", 60, false],
  ["Prulifloxacin", "Percin", "600 mg", "tablet", "tablets", "Antibiotic", 60, false],
  ["Sparfloxacin", "Sparx", "200 mg", "tablet", "tablets", "Antibiotic", 60, false],
  ["Lomefloxacin", "Lomef", "400 mg", "tablet", "tablets", "Antibiotic", 60, false],
  ["Pefloxacin", "Pelox", "400 mg", "tablet", "tablets", "Antibiotic", 60, false],
  ["Roxithromycin", "Roxid", "300 mg", "tablet", "tablets", "Antibiotic", 80, false],
  ["Clarithromycin", "Claribid", "250 mg", "tablet", "tablets", "Antibiotic", 100, true],
  ["Azithromycin", "Azithral", "500 mg", "injection", "vials", "Antibiotic", 80, true],
  ["Amoxicillin + Clavulanic Acid", "Augmentin", "375 mg", "tablet", "tablets", "Antibiotic", 150, true],
  ["Amoxicillin + Clavulanic Acid", "Augmentin", "1.2 g", "injection", "vials", "Antibiotic", 150, true],
  ["Ampicillin", "Roscillin", "500 mg", "capsule", "capsules", "Antibiotic", 120, true],
  ["Ampicillin + Cloxacillin", "Megapen", "500 mg", "capsule", "capsules", "Antibiotic", 120, true],
  ["Amoxicillin + Cloxacillin", "Novaclox", "500 mg", "capsule", "capsules", "Antibiotic", 120, true],
  ["Piperacillin + Tazobactam", "Piptaz", "4.5 g", "injection", "vials", "Antibiotic", 100, true],
  ["Ticarcillin + Clavulanic Acid", "Timentin", "3.1 g", "injection", "vials", "Antibiotic", 60, false],
  ["Cefoperazone + Sulbactam", "Magnex", "1.5 g", "injection", "vials", "Antibiotic", 100, true],
  ["Ceftriaxone + Sulbactam", "Oframax Forte", "1.5 g", "injection", "vials", "Antibiotic", 100, true],
  ["Cefepime + Tazobactam", "Zepime", "1.125 g", "injection", "vials", "Antibiotic", 60, false],
  ["Meropenem + Sulbactam", "Meromac Plus", "1.5 g", "injection", "vials", "Antibiotic", 60, false],
  ["Imipenem + Cilastatin", "Tienam", "500 mg", "injection", "vials", "Antibiotic", 80, true],
  ["Doripenem", "Doribax", "500 mg", "injection", "vials", "Antibiotic", 40, false],
  ["Biapenem", "Biapex", "300 mg", "injection", "vials", "Antibiotic", 40, false],
  ["Ketoconazole", "Nizral", "200 mg", "tablet", "tablets", "Antifungal", 100, true],
  ["Itraconazole", "Canditral", "200 mg", "capsule", "capsules", "Antifungal", 100, true],
  ["Fluconazole", "Syscan", "200 mg", "tablet", "tablets", "Antifungal", 100, true],
  ["Voriconazole", "Vfend", "50 mg", "tablet", "tablets", "Antifungal", 60, false],
  ["Voriconazole", "Vfend", "200 mg", "injection", "vials", "Antifungal", 60, false],
  ["Posaconazole", "Noxafil", "40 mg / ml", "suspension", "bottles", "Antifungal", 40, false],
  ["Isavuconazole", "Cresemba", "100 mg", "capsule", "capsules", "Antifungal", 40, false],
  ["Amphotericin B Liposomal", "Ambisome", "50 mg", "injection", "vials", "Antifungal", 40, true],
  ["Amphotericin B Lipid Complex", "Abelcet", "50 mg", "injection", "vials", "Antifungal", 40, true],
  ["Caspofungin", "Cancidas", "70 mg", "injection", "vials", "Antifungal", 40, false],
  ["Micafungin", "Mycamine", "100 mg", "injection", "vials", "Antifungal", 40, false],
  ["Anidulafungin", "Eraxis", "100 mg", "injection", "vials", "Antifungal", 40, false],
  ["Griseofulvin", "Grisovin", "500 mg", "tablet", "tablets", "Antifungal", 80, false],
  ["Terbinafine", "Terbinaforce", "500 mg", "tablet", "tablets", "Antifungal", 80, true],
  ["Flucytosine", "Ancobon", "500 mg", "capsule", "capsules", "Antifungal", 40, false],
  ["Nystatin", "Mycostatin", "500,000 IU", "tablet", "tablets", "Antifungal", 80, true],
  ["Nystatin", "Mycostatin", "100,000 IU / ml", "suspension", "bottles", "Antifungal", 80, true],
  ["Clotrimazole", "Candid", "100 mg", "suppository", "suppositories", "Antifungal", 100, true],
  ["Miconazole", "Gyno-Daktarin", "200 mg", "suppository", "suppositories", "Antifungal", 100, true],
  ["Acyclovir", "Zovirax", "200 mg", "tablet", "tablets", "Antiviral", 100, true],
  ["Acyclovir", "Zovirax", "800 mg", "tablet", "tablets", "Antiviral", 100, true],
  ["Acyclovir", "Zovirax", "5%", "cream", "tubes", "Antiviral", 100, true],
  ["Valacyclovir", "Valcivir", "1000 mg", "tablet", "tablets", "Antiviral", 80, false],
  ["Famciclovir", "Famtrex", "500 mg", "tablet", "tablets", "Antiviral", 60, false],
  ["Penciclovir", "Denavir", "1%", "cream", "tubes", "Antiviral", 60, false],
  ["Ganciclovir", "Cytovene", "500 mg", "injection", "vials", "Antiviral", 60, true],
  ["Valganciclovir", "Valcyte", "450 mg", "tablet", "tablets", "Antiviral", 60, true],
  ["Foscarnet", "Foscavir", "24 mg / ml", "injection", "bottles", "Antiviral", 40, false],
  ["Cidofovir", "Vistide", "75 mg / ml", "injection", "vials", "Antiviral", 40, false],
  ["Oseltamivir", "Antiflu", "12 mg / ml", "suspension", "bottles", "Antiviral", 80, true],
  ["Zanamivir", "Relenza", "5 mg", "inhaler", "inhalers", "Antiviral", 60, false],
  ["Peramivir", "Rapivab", "200 mg", "injection", "vials", "Antiviral", 40, false],
  ["Baloxavir", "Xofluza", "40 mg", "tablet", "tablets", "Antiviral", 40, false],
  ["Ribavirin", "Rebetol", "200 mg", "capsule", "capsules", "Antiviral", 60, true],
  ["Tenofovir Alafenamide", "Vemlidy", "25 mg", "tablet", "tablets", "Antiviral", 80, false],
  ["Entecavir", "Entavir", "1 mg", "tablet", "tablets", "Antiviral", 60, false],
  ["Lamivudine", "Lamivir", "100 mg", "tablet", "tablets", "Antiviral", 100, true],
  ["Telbivudine", "Sebivo", "600 mg", "tablet", "tablets", "Antiviral", 40, false],
  ["Adefovir", "Hepsera", "10 mg", "tablet", "tablets", "Antiviral", 40, false],
  ["Sofosbuvir + Velpatasvir", "Epclusa", "400/100 mg", "tablet", "tablets", "Antiviral", 60, false],
  ["Ledipasvir + Sofosbuvir", "Harvoni", "90/400 mg", "tablet", "tablets", "Antiviral", 60, false],
  ["Daclatasvir", "Daklinza", "60 mg", "tablet", "tablets", "Antiviral", 60, false],
  ["Glecaprevir + Pibrentasvir", "Mavyret", "100/40 mg", "tablet", "tablets", "Antiviral", 40, false],
  ["Zidovudine", "Retrovir", "300 mg", "tablet", "tablets", "Antiviral", 100, true],
  ["Stavudine", "Zerit", "30 mg", "capsule", "capsules", "Antiviral", 80, false],
  ["Didanosine", "Videx", "400 mg", "capsule", "capsules", "Antiviral", 60, false],
  ["Abacavir", "Ziagen", "300 mg", "tablet", "tablets", "Antiviral", 80, true],
  ["Emtricitabine", "Emtriva", "200 mg", "capsule", "capsules", "Antiviral", 80, true],
  ["Tenofovir + Emtricitabine", "Truvada", "300/200 mg", "tablet", "tablets", "Antiviral", 100, true],
  ["Efavirenz", "Sustiva", "600 mg", "tablet", "tablets", "Antiviral", 80, true],
  ["Nevirapine", "Viramune", "200 mg", "tablet", "tablets", "Antiviral", 80, true],
  ["Etravirine", "Intelence", "200 mg", "tablet", "tablets", "Antiviral", 60, false],
  ["Rilpivirine", "Edurant", "25 mg", "tablet", "tablets", "Antiviral", 60, false],
  ["Doravirine", "Pifeltro", "100 mg", "tablet", "tablets", "Antiviral", 40, false],
  ["Lopinavir + Ritonavir", "Kaletra", "200/50 mg", "tablet", "tablets", "Antiviral", 80, true],
  ["Atazanavir", "Reyataz", "300 mg", "capsule", "capsules", "Antiviral", 60, false],
  ["Darunavir", "Prezista", "600 mg", "tablet", "tablets", "Antiviral", 60, false],
  ["Ritonavir", "Norvir", "100 mg", "tablet", "tablets", "Antiviral", 80, true],
  ["Raltegravir", "Isentress", "400 mg", "tablet", "tablets", "Antiviral", 60, false],
  ["Dolutegravir", "Tivicay", "50 mg", "tablet", "tablets", "Antiviral", 80, true],
  ["Bictegravir", "Biktarvy", "50 mg", "tablet", "tablets", "Antiviral", 40, false],
  ["Maraviroc", "Selzentry", "300 mg", "tablet", "tablets", "Antiviral", 40, false],
  ["Enfuvirtide", "Fuzeon", "90 mg", "injection", "vials", "Antiviral", 20, false],
  ["Ibalizumab", "Trogarzo", "200 mg", "injection", "vials", "Antiviral", 20, false],
  ["Fostemsavir", "Rukobia", "600 mg", "tablet", "tablets", "Antiviral", 20, false],
  ["Lenacapavir", "Sunlenca", "300 mg", "tablet", "tablets", "Antiviral", 20, false],
  ["Nirmatrelvir + Ritonavir", "Paxlovid", "150/100 mg", "tablet", "tablets", "Antiviral", 60, true],
  ["Molnupiravir", "Lagevrio", "200 mg", "capsule", "capsules", "Antiviral", 60, true],
  ["Remdesivir", "Veklury", "100 mg", "injection", "vials", "Antiviral", 80, true],
  ["Tocilizumab", "Actemra", "400 mg", "injection", "vials", "Immunology", 40, true],
  ["Baricitinib", "Olumiant", "4 mg", "tablet", "tablets", "Immunology", 40, false],
  ["Tofacitinib", "Xeljanz", "5 mg", "tablet", "tablets", "Immunology", 40, false],
  ["Upadacitinib", "Rinvoq", "15 mg", "tablet", "tablets", "Immunology", 40, false],
  ["Abrocitinib", "Cibinqo", "100 mg", "tablet", "tablets", "Immunology", 20, false],
  ["Apremilast", "Otezla", "30 mg", "tablet", "tablets", "Immunology", 40, false],
  ["Secukinumab", "Cosentyx", "150 mg", "injection", "syringes", "Immunology", 40, false],
  ["Ixekizumab", "Taltz", "80 mg", "injection", "syringes", "Immunology", 40, false],
  ["Brodalumab", "Siliq", "210 mg", "injection", "syringes", "Immunology", 20, false],
  ["Guselkumab", "Tremfya", "100 mg", "injection", "syringes", "Immunology", 20, false],
  ["Tildrakizumab", "Ilumya", "100 mg", "injection", "syringes", "Immunology", 20, false],
  ["Risankizumab", "Skyrizi", "150 mg", "injection", "syringes", "Immunology", 20, false],
  ["Ustekinumab", "Stelara", "45 mg", "injection", "syringes", "Immunology", 40, false],
  ["Vedolizumab", "Entyvio", "300 mg", "injection", "vials", "Immunology", 40, false],
  ["Natalizumab", "Tysabri", "300 mg", "injection", "vials", "Immunology", 20, false],
  ["Ocrelizumab", "Ocrevus", "300 mg", "injection", "vials", "Immunology", 20, false],
  ["Alemtuzumab", "Lemtrada", "12 mg", "injection", "vials", "Immunology", 20, false],
  ["Cladribine", "Mavenclad", "10 mg", "tablet", "tablets", "Immunology", 20, false],
  ["Fingolimod", "Gilenya", "0.5 mg", "capsule", "capsules", "Immunology", 40, false],
  ["Siponimod", "Mayzent", "2 mg", "tablet", "tablets", "Immunology", 20, false],
  ["Ozanimod", "Zeposia", "0.92 mg", "capsule", "capsules", "Immunology", 20, false],
  ["Ponesimod", "Ponvory", "20 mg", "tablet", "tablets", "Immunology", 20, false],
  ["Teriflunomide", "Aubagio", "14 mg", "tablet", "tablets", "Immunology", 40, false],
  ["Dimethyl Fumarate", "Tecfidera", "240 mg", "capsule", "capsules", "Immunology", 40, false],
  ["Diroximel Fumarate", "Vumerity", "231 mg", "capsule", "capsules", "Immunology", 20, false],
  ["Monomethyl Fumarate", "Bafiertam", "95 mg", "capsule", "capsules", "Immunology", 20, false],
  ["Glatiramer Acetate", "Copaxone", "20 mg", "injection", "syringes", "Immunology", 40, false],
  ["Interferon Beta-1a", "Avonex", "30 mcg", "injection", "syringes", "Immunology", 40, false],
  ["Interferon Beta-1b", "Betaseron", "0.25 mg", "injection", "vials", "Immunology", 40, false],
  ["Peginterferon Beta-1a", "Plegridy", "125 mcg", "injection", "syringes", "Immunology", 20, false],
  ["Ofatumumab", "Kesimpta", "20 mg", "injection", "syringes", "Immunology", 20, false],
  ["Eculizumab", "Soliris", "300 mg", "injection", "vials", "Immunology", 20, false],
  ["Ravulizumab", "Ultomiris", "300 mg", "injection", "vials", "Immunology", 20, false],
  ["Pegcetacoplan", "Empaveli", "1080 mg", "injection", "vials", "Immunology", 20, false],
  ["Iptacopan", "Fabhalta", "200 mg", "capsule", "capsules", "Immunology", 20, false],
  ["Danicopan", "Voydeya", "50 mg", "tablet", "tablets", "Immunology", 20, false],
  ["Sutimlimab", "Enjaymo", "1100 mg", "injection", "vials", "Immunology", 20, false],
  ["Efgartigimod", "Vyvgart", "400 mg", "injection", "vials", "Immunology", 20, false],
  ["Rozanolixizumab", "Rystiggo", "140 mg", "injection", "vials", "Immunology", 20, false],
  ["Zilucoplan", "Zilbrysq", "23 mg", "injection", "syringes", "Immunology", 20, false],
  ["Ravulizumab", "Ultomiris", "300 mg", "injection", "vials", "Immunology", 20, false],
  ["Satralizumab", "Enspryng", "120 mg", "injection", "syringes", "Immunology", 20, false],
  ["Inebilizumab", "Uplizna", "300 mg", "injection", "vials", "Immunology", 20, false],
  ["Belimumab", "Benlysta", "120 mg", "injection", "vials", "Immunology", 40, false],
  ["Anifrolumab", "Saphnelo", "300 mg", "injection", "vials", "Immunology", 20, false],
  ["Voclosporin", "Lupkynis", "7.9 mg", "capsule", "capsules", "Immunology", 20, false],
  ["Mycophenolate Mofetil", "CellCept", "500 mg", "tablet", "tablets", "Immunology", 80, true],
  ["Mycophenolic Acid", "Myfortic", "360 mg", "tablet", "tablets", "Immunology", 60, false],
  ["Azathioprine", "Imuran", "50 mg", "tablet", "tablets", "Immunology", 100, true],
  ["Cyclosporine", "Sandimmune", "100 mg", "capsule", "capsules", "Immunology", 80, true],
  ["Tacrolimus", "Prograf", "1 mg", "capsule", "capsules", "Immunology", 80, true],
  ["Sirolimus", "Rapamune", "1 mg", "tablet", "tablets", "Immunology", 60, false],
  ["Everolimus", "Zortress", "0.75 mg", "tablet", "tablets", "Immunology", 60, false],
  ["Basiliximab", "Simulect", "20 mg", "injection", "vials", "Immunology", 40, false],
  ["Antithymocyte Globulin (Rabbit)", "Thymoglobulin", "25 mg", "injection", "vials", "Immunology", 40, false],
  ["Antithymocyte Globulin (Equine)", "Atgam", "250 mg", "injection", "vials", "Immunology", 40, false],
  ["Alemtuzumab", "Campath", "30 mg", "injection", "vials", "Immunology", 20, false],
  ["Bortezomib", "Velcade", "3.5 mg", "injection", "vials", "Oncology", 60, true],
  ["Carfilzomib", "Kyprolis", "60 mg", "injection", "vials", "Oncology", 40, false],
  ["Ixazomib", "Ninlaro", "4 mg", "capsule", "capsules", "Oncology", 40, false],
  ["Lenalidomide", "Revlimid", "25 mg", "capsule", "capsules", "Oncology", 60, true],
  ["Pomalidomide", "Pomalyst", "4 mg", "capsule", "capsules", "Oncology", 40, false],
  ["Thalidomide", "Thalomid", "100 mg", "capsule", "capsules", "Oncology", 60, true],
  ["Daratumumab", "Darzalex", "100 mg", "injection", "vials", "Oncology", 40, false],
  ["Isatuximab", "Sarclisa", "100 mg", "injection", "vials", "Oncology", 20, false],
  ["Elotuzumab", "Empliciti", "300 mg", "injection", "vials", "Oncology", 20, false],
  ["Panobinostat", "Farydak", "20 mg", "capsule", "capsules", "Oncology", 20, false],
  ["Selinexor", "Xpovio", "20 mg", "tablet", "tablets", "Oncology", 20, false],
  ["Belantamab Mafodotin", "Blenrep", "100 mg", "injection", "vials", "Oncology", 20, false],
  ["Teclistamab", "Tecvayli", "30 mg", "injection", "vials", "Oncology", 20, false],
  ["Elranatamab", "Elrexfio", "76 mg", "injection", "vials", "Oncology", 20, false],
  ["Talquetamab", "Talvey", "3 mg", "injection", "vials", "Oncology", 20, false],
  ["Ibrutinib", "Imbruvica", "140 mg", "capsule", "capsules", "Oncology", 60, true],
  ["Acalabrutinib", "Calquence", "100 mg", "capsule", "capsules", "Oncology", 40, false],
  ["Zanubrutinib", "Brukinsa", "80 mg", "capsule", "capsules", "Oncology", 40, false],
  ["Pirtobrutinib", "Jaypirca", "100 mg", "tablet", "tablets", "Oncology", 20, false],
  ["Venetoclax", "Venclexta", "100 mg", "tablet", "tablets", "Oncology", 40, false],
  ["Obinutuzumab", "Gazyva", "1000 mg", "injection", "vials", "Oncology", 40, false],
  ["Rituximab", "Rituxan", "100 mg", "injection", "vials", "Oncology", 60, true],
  ["Ofatumumab", "Arzerra", "100 mg", "injection", "vials", "Oncology", 20, false],
  ["Idelalisib", "Zydelig", "150 mg", "tablet", "tablets", "Oncology", 20, false],
  ["Duvelisib", "Copiktra", "25 mg", "capsule", "capsules", "Oncology", 20, false],
  ["Copanlisib", "Aliqopa", "60 mg", "injection", "vials", "Oncology", 20, false],
  ["Umbralisib", "Ukoniq", "200 mg", "tablet", "tablets", "Oncology", 20, false],
  ["Axi-cel", "Yescarta", "Suspension", "injection", "bags", "Oncology", 10, false],
  ["Tisa-cel", "Kymriah", "Suspension", "injection", "bags", "Oncology", 10, false],
  ["Brexu-cel", "Tecartus", "Suspension", "injection", "bags", "Oncology", 10, false],
  ["Liso-cel", "Breyanzi", "Suspension", "injection", "bags", "Oncology", 10, false],
  ["Cilta-cel", "Carvykti", "Suspension", "injection", "bags", "Oncology", 10, false],
  ["Ide-cel", "Abecma", "Suspension", "injection", "bags", "Oncology", 10, false],
  ["Midostaurin", "Rydapt", "25 mg", "capsule", "capsules", "Oncology", 20, false],
  ["Gilteritinib", "Xospata", "40 mg", "tablet", "tablets", "Oncology", 20, false],
  ["Quizartinib", "Vanflyta", "26.5 mg", "tablet", "tablets", "Oncology", 20, false],
  ["Enasidenib", "Idhifa", "100 mg", "tablet", "tablets", "Oncology", 20, false],
  ["Ivosidenib", "Tibsovo", "250 mg", "tablet", "tablets", "Oncology", 20, false],
  ["Olutasidenib", "Rezlidhia", "150 mg", "capsule", "capsules", "Oncology", 20, false],
  ["Glasdegib", "Daurismo", "100 mg", "tablet", "tablets", "Oncology", 20, false],
  ["Venetoclax", "Venclexta", "50 mg", "tablet", "tablets", "Oncology", 40, false],
  ["Azacitidine", "Vidaza", "100 mg", "injection", "vials", "Oncology", 60, true],
  ["Decitabine", "Dacogen", "50 mg", "injection", "vials", "Oncology", 60, true],
  ["Cytarabine", "Cytosar-U", "100 mg", "injection", "vials", "Oncology", 60, true],
  ["Daunorubicin", "Cerubidine", "20 mg", "injection", "vials", "Oncology", 60, true],
  ["Idarubicin", "Idamycin", "5 mg", "injection", "vials", "Oncology", 40, false],
  ["Mitoxantrone", "Novantrone", "20 mg", "injection", "vials", "Oncology", 40, false],
  ["Etoposide", "Vepesid", "100 mg", "injection", "vials", "Oncology", 60, true],
  ["Teniposide", "Vumon", "50 mg", "injection", "vials", "Oncology", 20, false],
  ["Fludarabine", "Fludara", "50 mg", "injection", "vials", "Oncology", 60, true],
  ["Cladribine", "Leustatin", "10 mg", "injection", "vials", "Oncology", 40, false],
  ["Nelarabine", "Arranon", "250 mg", "injection", "vials", "Oncology", 20, false],
  ["Clofarabine", "Clolar", "20 mg", "injection", "vials", "Oncology", 20, false],
  ["Pentostatin", "Nipent", "10 mg", "injection", "vials", "Oncology", 20, false],
  ["Mercaptopurine", "Purinethol", "50 mg", "tablet", "tablets", "Oncology", 60, true],
  ["Thioguanine", "Tabloid", "40 mg", "tablet", "tablets", "Oncology", 40, false],
  ["Hydroxyurea", "Hydrea", "500 mg", "capsule", "capsules", "Oncology", 80, true],
  ["Imatinib", "Gleevec", "400 mg", "tablet", "tablets", "Oncology", 80, true],
  ["Dasatinib", "Sprycel", "100 mg", "tablet", "tablets", "Oncology", 60, false],
  ["Nilotinib", "Tasigna", "200 mg", "capsule", "capsules", "Oncology", 60, false],
  ["Bosutinib", "Bosulif", "500 mg", "tablet", "tablets", "Oncology", 40, false],
  ["Ponatinib", "Iclusig", "45 mg", "tablet", "tablets", "Oncology", 40, false],
  ["Asciminib", "Scemblix", "40 mg", "tablet", "tablets", "Oncology", 40, false],
  ["Omacetaxine", "Synribo", "3.5 mg", "injection", "vials", "Oncology", 20, false],
  ["Ruxolitinib", "Jakafi", "20 mg", "tablet", "tablets", "Oncology", 40, false],
  ["Fedratinib", "Inrebic", "100 mg", "capsule", "capsules", "Oncology", 20, false],
  ["Pacritinib", "Vonjo", "100 mg", "capsule", "capsules", "Oncology", 20, false],
  ["Momelotinib", "Ojjaara", "100 mg", "tablet", "tablets", "Oncology", 20, false],
  ["Ropeginterferon alfa-2b", "Besremi", "500 mcg", "injection", "syringes", "Oncology", 20, false],
  ["Pemigatinib", "Pemazyre", "13.5 mg", "tablet", "tablets", "Oncology", 20, false],
  ["Infigratinib", "Truseltiq", "100 mg", "capsule", "capsules", "Oncology", 20, false],
  ["Futibatinib", "Lytgobi", "4 mg", "tablet", "tablets", "Oncology", 20, false],
  ["Erdafitinib", "Balversa", "4 mg", "tablet", "tablets", "Oncology", 20, false],
  ["Sotorasib", "Lumakras", "120 mg", "tablet", "tablets", "Oncology", 20, false],
  ["Adagrasib", "Krazati", "200 mg", "tablet", "tablets", "Oncology", 20, false],
  ["Osimertinib", "Tagrisso", "80 mg", "tablet", "tablets", "Oncology", 60, false],
  ["Amivantamab", "Rybrevant", "350 mg", "injection", "vials", "Oncology", 20, false],
  ["Mobocertinib", "Exkivity", "40 mg", "capsule", "capsules", "Oncology", 20, false],
  ["Afatinib", "Gilotrif", "40 mg", "tablet", "tablets", "Oncology", 40, false],
  ["Dacomitinib", "Vizimpro", "45 mg", "tablet", "tablets", "Oncology", 20, false],
  ["Alectinib", "Alecensa", "150 mg", "capsule", "capsules", "Oncology", 40, false],
  ["Brigatinib", "Alunbrig", "180 mg", "tablet", "tablets", "Oncology", 40, false],
  ["Lorlatinib", "Lorbrena", "100 mg", "tablet", "tablets", "Oncology", 40, false],
  ["Crizotinib", "Xalkori", "250 mg", "capsule", "capsules", "Oncology", 40, false],
  ["Ceritinib", "Zykadia", "150 mg", "capsule", "capsules", "Oncology", 40, false],
  ["Entrectinib", "Rozlytrek", "200 mg", "capsule", "capsules", "Oncology", 20, false],
  ["Larotrectinib", "Vitrakvi", "100 mg", "capsule", "capsules", "Oncology", 20, false],
  ["Repotrectinib", "Augtyro", "40 mg", "capsule", "capsules", "Oncology", 20, false],
  ["Selpercatinib", "Retevmo", "80 mg", "capsule", "capsules", "Oncology", 20, false],
  ["Pralsetinib", "Gavreto", "100 mg", "capsule", "capsules", "Oncology", 20, false],
  ["Capmatinib", "Tabrecta", "200 mg", "tablet", "tablets", "Oncology", 20, false],
  ["Tepotinib", "Tepmetko", "225 mg", "tablet", "tablets", "Oncology", 20, false],
  ["Savolitinib", "Orpathys", "200 mg", "tablet", "tablets", "Oncology", 20, false]
] as const;
